# Generated by Django 4.2.3 on 2023-07-11 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='task_date',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='task_description',
        ),
    ]
